Financial-Times/n-ui-foundations

- typography/main.scss
There are no user-facing products relying on this, so _should_ be a safe
way to save a few CSS bytes.
> Put o-typography back to silent mode

- typography/main.scss
o-typography no longer uses `o-typography--loaded-x` classes. Now it’s
kind-of reversed, where it [outputs extra styles for the loading state instead](https://github.com/Financial-Times/o-typography/blob/master/src/scss/_mixins.scss#L91). However, we seem to be getting on fine without them, so let’s just remove these bits rather than replace them.
> Remove old o-typography styles

- normalize/main.scss
A baby step towards [moving over to o-normalise](https://github.com/Financial-Times/o-normalise/blob/0a9fa7a69543e4248d2b7024d688e2e8648bc085/src/scss/_mixins.scss#L69) that happens to cater to our immediate needs 😬 (fixes firefox rendering of the myFT section on the front page)
> Smooth out text in macOS Firefox

- main.scss
The mobile app requires n-feedback (see https://jira.ft.com/browse/AT-2096) which depends on n-ui-foundation but doesn't require styles to be applied.
> Enable dependent projects to import n-ui-foundation without applying styles

- typography/main.scss
Adds MetricWeb `medium` (500) font face. This **does not** include a new font file, as it uses the same font file as the `semibold` (600) font face.
Stream pages include `o-teaser` which uses `font-weight: 500` in its label, however no font face for a weight of 500 is included in the head of the stream page. The effect is a thin looking label:
Which should look like this:
> Add MetricWeb medium font face.

- bower.json
o-date was recently migrated to v3 (n-ui-foundations@v3.1.0).
This has caused conflicts for projects which depend on
n-ui-foundations and o-date@v2. I.e. builds may fail,
requiring user intervention, and build service requests may
also fail (impacting production apps).
Here's one I've seen:
`/v2/bundles/js?modules=o-grid@^4.3.7,o-colors@^4.1.5,o-normalise@^1.5.3,o-footer@^6.0.8,o-header-services@^2.0.5,o-fonts@^3.0.4,o-typography@^5.4.2,o-table@^6.5.0,o-forms@^5.0.1,o-buttons@^5.8.5,o-overlay@^2.2.0,o-date@^2.10.3,n-alert-banner@^1.0.0,o-tracking@^1.3.8,o-tooltip@^3.1.2`
_(n-alert-banner requires n-ui-foundations)_
As o-date v2 and v3 have the same interface we can use a range
to allow either.
Alternatively, we would have to revert and release a major of
n-ui-foundations.
> Support o-date v2 or v3.

- README.md
- grid/main.scss
The snappy grid has a container which is smaller than the viewport
at each breakpoint [see snappy grid demo](https://www.ft.com/__origami/service/build/v2/demos/o-grid@4.5.3/snappy).
The standard fluid grid is always full bleed at each breakpoint,
until the max container size is reached [see fluid grid demo](https://www.ft.com/__origami/service/build/v2/demos/o-grid@4.5.3/default).
The snappy grid is deprecated and not recommended for new projects.
Going forward not all projects that use `n-ui-foundations` want
to use use a snappy grid, for example `ft-app`.
As this changes the layout of projects it should be considered
a breaking change in case it causes visually regressions. The
snappy grid is still available however so the migration step
is low cost (two find and replaces). For …
> Do not output a snappy grid by default.

- README.md
Some clarifying notes about the change required to maintain snappy grid until we decide to move to using a fluid grid.
> Upgrade README v5 to v6 migration guide

- .circleci/config.yml
- package.json
Please run appropriate tests and checks to ensure that the app is compatible with this Node version. https://node.green is a useful reference.<br/><br/>This PR was created using a [nori](https://github.com/Financial-Times/nori) script 🍙<br/><br/>*Nori is a command-line application for managing changes across multiple (usually Github) repositories.*
> Upgrade Node to v14

- .circleci/config.yml
- package.json
After starting the upgrade to Node v14, I noticed that Serverless apps can only go as high as v12 because that is the latest Node version available for AWS Lambda.
I then encountered these excellent points raised by Simon Plenderleith https://github.com/Financial-Times/tooling-helpers/issues/60, which is essentially that packages should ensure compatibility with all version of Node on which they can run, which will be dictated by the apps consuming them.
To do this will increase build time as the process is duplicated for two Node versions, triplicated for three Node versions, etc. (example [here](https://github.com/adambraimbridge/asari/blob/d0fc553903e7c7d2e6e796e35f8b5e015eabc672/.circleci/config.yml)). Platforms is currently trying to reduce CI build times so to do this would be …
> Use Node v12

- .circleci/config.yml
- package.json
As pointed out by @emortong in https://github.com/Financial-Times/n-ui-foundations/pull/92#issuecomment-734877955, there does not seem to be a reason as to why `chai` and `mocha` were added as `dependencies` rather than `devDependencies` back in this early PR https://github.com/Financial-Times/n-ui-foundations/pull/2.
Moving them into `devDependencies` also removes them from Snyk's analysis and means we won't need to worry about doing any vulnerability upgrades.
As this change will leave this repo's `package.json` without any `dependencies`, it means the `npx snyk monitor` command will fail, and so that command has also been removed.
> Set chai + mocha as devDependencies (i.e. not dependencies)

- .circleci/config.yml
- README.md
[Ticket CPP-442 Upgrade GitHub repos from `master` to `main`](https://financialtimes.atlassian.net/browse/CPP-442)<br/><br/>As an organisation we are moving away from the usage of `master` as a central branch and switching it to `main`, this is to avoid using unnecessary language that can be offensive. This PR is for making those changes. <br/><br/>This PR was created using a nori script<br/><br/>_Nori is a command-line application for managing changes across multiple (usually Github) repositories._
> CPP-442 Upgrade GitHub repos from master to main

- .circleci/config.yml
- karma.conf.js
- package-lock.json
- package.json
- test/sample-users.spec.js
We are moving to npm 7 so we are ready to migrate away from bower.
From my notes:
> This project was depending on mix of sinon and chai plugins, some depending on mismatching peers. karma-sinon-chai is the main culprit, as it released a breaking change to bump it's sinon dependency to a new major version... in a minor release! So that caught us out seeing as we were using the default caret range for the package. However, forcing it back to the proper minor version with a tilde range showed it then required an older version of chai than we were using (looks like we mistakenly accepted a renovate PR to update it a few years back.) In the end I bumped karma-sinon-chai up to the breaking minor version and then also bumped sinon to v2 so that everything matched up. Seemed better than going …
> Update to npm 7 and fix peer dependency conflicts

- .circleci/config.yml
- package-lock.json
- package.json
These images will be EOL from Dec 31st, and we should migrate to the modern cimg/* equivalents.
> CPP-642 / CPP-699 migrate from circleci/* to cimg/*

- package-lock.json
- package.json
PageKit requires these missing packages which were removed unintentionally as part of Bower to NPM migration
> add ftdomdelegate and superstore

- package-lock.json
- package.json
Two changes to enforcing the right version of node and npm with `check-engines`:
1. Improve compatibility of check-engines guard: some shells in use (particularly in our CI and build images) do not support the non-POSIX `[[` command, so use the more portable `[` built-in instead.
2. Allow npm 8: the only breaking change in npm8 is dropping support for `node<12`, but we already require `node@12` so this doesn't affect us and will allow for newer npm versions to be used.
> Fix issues with engines enforcement

- package-lock.json
- package.json
To ensure compatibility with apps that will also be depending on these Origami components (or their dependencies), they should be installed as peerDependencies, and additionally as devDependencies for local development and testing. In the future, it may be possible to make the peer deps more permissive, but at this point we have a specific version that we've migrated to from bower.
> cpp-748 moving origami components to peer and dev deps

- package-lock.json
- package.json
The `superstore`, `superstore-sync`, and `ftdomdelegate` packages were being installed as dependencies for `n-ui-foundations`, but are not actually used anywhere in the code. Rather than this being a simple case of deleting superfluous dependencies, however, this is a holdover feature from the project's time as a bower dependency, where those three dependencies could be installed and used via this package. Using transitive dependencies like this is inappropriate and unstable: it makes the dependency chain hard to follow/audit, and leaves dependents subject to breaking if any of the transitive dependencies are updated or removed from `n-ui-foundations`. Instead, they should be installed as direct dependencies of packages that need them.
> CPP-668 Delete dependencies that were only being used transitively

- _mixins.scss
Removed o-assets-global-path reference to Build Service v2 used for $o-assets-global-path. o-assets is deprecated, and doesn't work at all with Build Service v3,
> removed o-assets-global-path referece

- _mixins.scss
i decided where it should live: nowhere
there were only a handful of remaining uses, which will soon all be replaced with `o-spacing`
> feat!: remove $spacing-unit

- _mixins.scss
were previously used for CSS code splitting but are no longer in use at all https://github.com/search?q=org%3AFinancial-Times+nUiStylesheet+language%3ASCSS+-repo%3Afinancial-times%2Fdotcom-page-kit+-repo%3Afinancial-times%2Fn-ui+-repo%3Afinancial-times%2Fn-ui-foundations+-is%3Aarchived&type=code
> Remove code splitting mixins

- typography/main.scss
getting pretty spicy now.
as far as i can tell, this bit of code has existed since 2014, and has been dutifully kept in place across several rounds of moving the code around without anyone wondering if it's actually worth keeping.
it was added to `n-ui-foundations` [in 2017](https://github.com/Financial-Times/n-ui-foundations/commit/aa76cbdce29758ef157a9598a972b4d4d2a86f04), when the repo was first split out from `n-ui`. in that repo it was added (as `0.82em`) in a commit called "[ported typography from next-sass-setup](https://github.com/Financial-Times/n-ui/commit/59621bbde46335b8d205a6c88b60ac77d03d3b07)". `next-sass-setup` was "archived" in 2015. this is before Github actually had an archive feature, so the process at the time was to move the repo to Bitbucket in a project called RIP. …
> feat!: remove default html font size
